import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AsideNav from "./components/Aside";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="bg-bg-cinza-claro grid grid-cols-[250px_1fr_1fr_1fr_1fr] grid-rows-[70px_1fr_1fr_1fr_1fr] gap-0 font-primary">
        <AsideNav />
        <Header />
        <div className="col-span-4 row-span-4 col-start-2 row-start-2">
          {children}
        </div>
      </body>
    </html>
  );
}
